name: Terraform CI
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Continuous Integration'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    - name: Terraform Init
      id: init
      run: terraform init
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
    - name: Azure Login
      id: login
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az config set core.only_show_error=false
          az login --use-device-code
    - name: chown
      run: sudo chown -R /home/runner/.azure
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false